def unique_letters(input_string):
    """Generate unique letters from the input string in the order of appearance."""
    seen_letters = set()  # Set to track seen letters
    
    for char in input_string:
        if char not in seen_letters:  
            seen_letters.add(char)    
            yield char                

# Test the generator
input_string = "hello"
gen = unique_letters(input_string)

# Print the unique letters generated by the generator
for letter in gen:
    print(letter, end=' ')
